name: Android CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: KSTOREFILE=../key.store KSTOREPWD=${{ secrets.KSTOREPWD }} KEYALIAS=${{ secrets.KEYALIAS }} KEYPWD=${{ secrets.KEYPWD }} ./gradlew build
    - run: find -type f -name '*.apk'

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: app/build/outputs/apk/alt/release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: vlatest
        files: app/build/outputs/apk/*/release/*.apk
